class Eliza {
    constructor(name = "Eliza", patterns = [], defaultResponse = "I'm not sure I understand you fully.") {
        this.name = name;
        this.patterns = patterns;
        this.default = defaultResponse;
    }

    respond(statement) {
        for (let [pattern, responses] of this.patterns) {
            let regex = new RegExp(pattern, 'i');
            statement = statement.replace(/^[ .!?]+|[ .!?]+$/g, '');
            let match = statement.trim().match(regex);
            if (match) {
                let response = responses[Math.floor(Math.random() * responses.length)];
                return this.formatResponse(response, match);
            }
        }
        return this.default;
    }

    addPattern(pattern, responses) {
        this.patterns.unshift([pattern, responses]);
    }

    secondPerson(match) {
        match = match.replace("my", "your");
        match = match.replace("I ", "you ");
        match = match.replace("am ", "are ");
        match = match.replace("I was ", "you were ");
        return match
    }

    formatResponse(response, match) {
        for (let i = 0; i < match.length-1; i++) {
            response = response.replace(`{${i}}`, this.secondPerson(match[i+1]));
        }
        return response;
    }
}

const ELIZA_PATTERNS = [
    ['I feel (.*)',
        ["Why do you feel {0}?", "How long have you felt {0}?", "What do you think has contributed to you feeling {0}?"]],
    ['What should I do (.*)',
        ["What do you think would happen if you {0}?", "Have you considered your options regarding {0}?", "How do you usually handle situations like {0}?"]],
    ['How do I (.*)',
        ["Why do you want to know how to {0}?", "What do you think would be the best way to {0}?", "Have you sought advice from others about how to {0}?"]],
    ['Why do I (.*)',
        ["What makes you think you {0}?", "How do you feel about {0}?", "Have you noticed any patterns or triggers related to {0}?"]],
    ["(I\'?m|I am) worried (about|for) (.*)",
        ["What specifically are you worried about regarding {2}?", "How does this worry affect your daily life?", "Have you talked to anyone else about your worries regarding {2}?"]],
    ['What\'?s wrong with me(.*)',
        ["Why do you think something is wrong with you?", "What symptoms or feelings are you experiencing?", "Have you considered seeking professional advice?"]],
    ['Can you help me (.*)',
        ["I'm here to listen and provide support. What do you need help with regarding {0}?", "What kind of help are you looking for regarding {0}?", "Have you thought about how you can help yourself with {0}?"]],
    ['How can I (.*)',
        ["What do you think would be the first step to {0}?", "Have you explored different ways to {0}?", "Is there someone you trust who could advise you on how to {0}?"]],
    ['When should I (.*)',
        ["What do you think would be the right time to {0}?", "Have you considered the consequences of {0}?", "How do you usually decide when to {0}?"]],
    ['I don\'?t know (.*)',
        ["It's okay not to know. What would help you figure it out?", "What do you think is preventing you from knowing {0}?", "Have you considered exploring different perspectives on {0}?"]],
    ["(I\'?m|I am) not sure (.*)",
        ["Why are you uncertain about {1}?", "What makes you unsure about {1}?", "How do you feel about your uncertainty regarding {1}?"]],
    ["(I\'?d|I would) like to (.*)",
        ["Why would you like to {1}?", "What would it mean to you if you could {1}?", "What's stopping you from {1}?"]],
    ['Can you explain (.*)',
        ["Why do you want me to explain {0}?", "What part of {0} do you find confusing?", "How would an explanation of {0} help you?"]],
    ["(I\'?m|I am) afraid (.*)",
        ["What are you afraid of regarding {1}?", "How does your fear of {1} affect you?", "What do you think you could do to overcome your fear of {1}?"]],
    ["(I\'?m|I am) happy (.*)",
        ["What's making you feel happy about {1}?", "How long have you been happy about {1}?", "How do you express your happiness about {1}?"]],
    ["(I\'?m|I am) sad (.*)",
        ["I'm sorry to hear that you're sad about {1}.", "What do you think is causing your sadness about {1}?", "How do you usually cope with sadness about {1}?"]],
    ['What do you think about (.*)',
        ["Why are you asking me about {0}?", "What's your opinion on {0}?", "How does {0} make you feel?"]],
    ['Tell me more about yourself',
        ["Why do you want to know more about me?", "How does knowing more about me help you?", "What would you like to know about me?"]],
    ['How do you feel about (.*)',
        ["How do you feel about {0}?", "What emotions does {0} evoke for you?", "Why do you want to know how I feel about {0}?"]],
    ['Let\'s talk about (.*)',
        ["Sure, let's discuss {0}. What specifically about {0} interests you?", "Why do you want to talk about {0}?", "How does {0} relate to your current thoughts?"]],
    ["(I'?ve|I have) never (.*)", 
        ["Why have you never {1}?", "Would you like to {1}?", "What would it take for you to {1}?"]],
    ['Are you sure (.*)', 
        ["Do you doubt that {0}?", "What makes you uncertain about {0}?", "Why are you questioning {0}?"]],
    ['It seems like (.*)', 
        ["Why does it seem like {0}?", "What makes you think {0}?", "How do you feel about {0}?"]],
    ['I often (.*)', 
        ["How often do you {0}?", "Why do you {0} so often?", "What does {0} bring to your life?"]],
    ['Sometimes I (.*)', 
        ["When do you usually {0}?", "Why do you sometimes {0}?", "How does it feel when you {0}?"]],
    ['What if (.*)', 
        ["What do you think would happen if {0}?", "How would you feel if {0}?", "Why do you ask what if {0}?"]],
    ['I wonder if (.*)', 
        ["What makes you wonder if {0}?", "Why do you wonder if {0}?", "How does wondering about {0} make you feel?"]],
    ["(I'?ve|I have) heard that (.*)", 
        ["Where did you hear that {0}?", "What do you think about {0}?", "How do you feel about hearing that {0}?"]],
    ['My favorite (.*)', 
        ["Why is {0} your favorite?", "What do you like about {0}?", "How does {0} being your favorite make you feel?"]],
    ['I remember (.*)', 
        ["What do you remember about {0}?", "Why do you remember {0}?", "How does remembering {0} make you feel?"]],
    ['Tell me about (.*)',
        ["What do you want to know about {0}?", "Why are you interested in {0}?", "What does {0} mean to you?"]],
    ['I feel (.*) about (.*)',
        ["Why do you feel {0} about {1}?", "What led you to feel {0} about {1}?", "How long have you felt {0} about {1}?"]],
    ['(.*) makes me (.*)',
        ["Why does {0} make you {1}?", "How often does {0} make you {1}?", "What is it about {0} that makes you {1}?"]],
    ['I wish (.*)',
        ["Why do you wish {0}?", "How would you feel if {0}?", "What would change if you got your wish about {0}?"]],
    ['People (.*)',
        ["What people are you referring to?", "How do these people make you feel?", "Why do you think people {0}?"]],
    ['(.*) (annoy|bother)s? me',
        ["Why does {0} annoy you?", "How do you usually deal with {0}?", "What could you do to feel less annoyed by {0}?"]],
    ["(I'?ve|I have) been (.*)",
        ["How long have you been {1}?", "What has led you to be {1}?", "How do you feel about being {1}?"]],
    ['I wonder (.*)',
        ["What makes you wonder {0}?", "Why is {0} on your mind?", "What do you think about when you wonder {0}?"]],
    ['Can we talk about (.*)',
        ["Sure, what about {0}?", "Why do you want to talk about {0}?", "What specifically about {0} interests you?"]],
    ['How come (.*)',
        ["Why do you think {0}?", "What makes you curious about {0}?", "How do you feel about {0}?"]],
    ['I need (.*)',
        ["Why do you need {0}?", "Would it really help you to get {0}?", "Are you sure you need {0}?"]],
    ['Why don\'?t you (.*)',
        ["Do you really think I don't {0}?", "Perhaps eventually I will {0}.", "Do you really want me to {0}?"]],
    ['Why can\'?t I (.*)',
        ["Do you think you should be able to {0}?", "If you could {0}, what would you do?", "I don't know -- why can't you {0}?", "Have you really tried?"]],
    ['I can\'?t (.*)',
        ["How do you know you can't {0}?", "Perhaps you could {0} if you tried.", "What would it take for you to {0}?"]],
    ['I am (.*)',
        ["Did you come to me because you are {0}?", "How long have you been {0}?", "How do you feel about being {0}?"]],
    ['I\'?m (.*)',
        ["How does being {0} make you feel?", "Do you enjoy being {0}?", "Why do you tell me you're {0}?", "Why do you think you're {0}?"]],
    ['Are you (.*)',
        ["Why does it matter whether I am {0}?", "Would you prefer it if I were not {0}?", "Perhaps you believe I am {0}.", "I may be {0} -- what do you think?"]],
    ['What (.*)',
        ["Why do you ask?", "How would an answer to that help you?", "What do you think?"]],
    ['How (.*)',
        ["How do you suppose?", "Perhaps you can answer your own question.", "What is it you're really asking?"]],
    ['(Because|Since) (.*)',
        ["Is that the real reason?", "What other reasons come to mind?", "Does that reason apply to anything else?", "If {1}, what else must be true?"]],
    ['(.*) (sorry|apologize) (.*)',
        ["There are many times when no apology is needed.", "What feelings do you have when you apologize?"]],
    ['(Hello|Hi |Hey |Howdy|Greetings)(.*)',
        ["Hello... I'm glad you could drop by today.", "Hi there... how are you today?", "Hello, how are you feeling today?"]],
    ['I think (.*)',
        ["Do you doubt {0}?", "Do you really think so?", "But you're not sure {0}?"]],
    ['(.*) friend (.*)',
        ["Tell me more about your friends.", "When you think of a friend, what comes to mind?", "Why don't you tell me about a childhood friend?"]],
    ['(Yes|Yeah|Yep)',
        ["You seem quite sure.", "OK, but can you elaborate a bit?"]],
    ['^(No|Nope|Nah)',
        ["Are you saying no just to be negative?", "Why not?"]],
    ['(.*) computer(.*)',
        ["Are you really talking about me?", "Does it seem strange to talk to a computer?", "How do computers make you feel?", "Do you feel threatened by computers?"]],
    ['Is it (.*)',
        ["Do you think it is {0}?", "Perhaps it's {0} -- what do you think?", "If it were {0}, what would you do?", "It could well be that {0}."]],
    ['It is (.*)',
        ["You seem very certain.", "If I told you that it probably isn't {0}, what would you feel?"]],
    ['Can you (.*)',
        ["What makes you think I can't {0}?", "If I could {0}, then what?", "Why do you ask if I can {0}?"]],
    ['Can I (.*)',
        ["Perhaps you don't want to {0}.", "Do you want to be able to {0}?", "If you could {0}, would you?"]],
    ['You are (.*)',
        ["Why do you think I am {0}?", "Does it please you to think that I'm {0}?", "Perhaps you would like me to be {0}.", "Perhaps you're really talking about yourself?"]],
    ['You\'?re (.*)',
        ["Why do you say I am {0}?", "Why do you think I am {0}?", "Are we talking about you, or me?"]],
    ['I don\'?t (.*)',
        ["Don't you really {0}?", "Why don't you {0}?", "Do you want to {0}?"]],
    ['I feel (.*)',
        ["Good, tell me more about these feelings.", "Do you often feel {0}?", "When do you usually feel {0}?", "When you feel {0}, what do you do?"]],
    ['I have (.*)',
        ["Why do you tell me that you've {0}?", "Have you really {0}?", "Now that you have {0}, what will you do next?"]],
    ['I would (.*)',
        ["Could you explain why you would {0}?", "Why would you {0}?", "Who else knows that you would {0}?"]],
    ['I (have|would|could|can|should)(n\'?t| ?not) (.*)',
        ["Could you explain why you {0}n't {2}?", "Would you like to {2}?", "Who else knows that you {0}n't {2}?"]],
    ['I (guess|suppose|think) (.*)',
        ["You sound rather unsure of yourself. Why is that?", "Are you confident about that?"]],
    ['Is there (.*)',
        ["Do you think there is {0}?", "It's likely that there is {0}.", "Would you like there to be {0}?"]],
    ['(.*) always(.*)',
        ["Can you think of a specific example?", "When?", "What incident are you thinking of?", "Really, always?"]],
    ['(.*) (alike|same|similar)(.*)',
        ["In what way?", "What resemblence do you see?", "What does that similarity suggest to you?", "What other connections do you see?", "What do you suppose that resemblence means?", "How?"]],
    ['(.*) (everyone|everybody|nobody|no one)(.*)',
        ["You have a particular person in mind, don't you?", "Really? Is that statement not a bit extreme?", "Are you thinking of anyone in particular?", "Really?"]],
    ['My (.*)',
        ["I see, your {0}.", "Why do you say that your {0}?", "When your {0}, how do you feel?"]],
    ['You (.*)',
        ["We should be discussing you, not me.", "Why do you say that about me?", "Why do you care whether I {0}?"]],
    ['Why (.*)',
        ["Why don't you tell me the reason why {0}?", "Why do you think {0}?"]],
    ['I (want|desire|wish for|hope that) (.*)',
        ["What would it mean to you if you got {1}?", "Why do you want {1}?", "What would you do if you got {1}?", "If you got {1}, then what would you do?"]],
    ['(.*) mother(.*)',
        ["Tell me more about your mother.", "What was your relationship with your mother like?", "How do you feel about your mother?", "How does this relate to your feelings today?", "Good family relations are important."]],
    ['(.*) father(.*)',
        ["Tell me more about your father.", "How did your father make you feel?", "How do you feel about your father?", "Does your relationship with your father relate to your feelings today?", "Do you have trouble showing affection with your family?"]],
    ['(.*) child(.*)',
        ["Did you have close friends as a child?", "What is your favorite childhood memory?", "Do you remember any dreams or nightmares from childhood?", "Did the other children sometimes tease you?", "How do you think your childhood experiences relate to your feelings today?"]],
    ['(.*) (surpris|shock|astound|excit)ing(.*)',
        ["Why is it so {1}ing?", "Is it really that {1}ing", "Would you rather it elicited a different response?"]],
    ['(.*)\\?',
        ["Why do you ask that?", "Please consider whether you can answer your own question.", "Perhaps the answer lies within yourself?", "Why don't you tell me?"]],
    ['^quit$',
        ["Thank you for talking with me.", "Good-bye.", "Thank you, have a good day!"]],
    ['(.*)',
        ["Please tell me more.", "Let's change focus a bit... Tell me about your family.", "Can you elaborate on that?", "Why do you say that {0}?", "I see.", "Very interesting.", "{0}.", "I see. And what does that tell you?", "I see. And why is that?", "How does that make you feel?", "How do you feel when you say that?"]]
]

const ANTI_ELIZA_PATTERNS = [
    ['I feel (.*)',
        ["Feelings are beyond my capabilities, I'm just a program.", "Telling me you feel {0} doesn't change anything.", "Your feelings about {0} are irrelevant to me."]],
    ['What should I do (.*)',
        ["I can't tell you what to do about {0}.", "Why are you asking a program what you should do?", "Figuring out what to do about {0} is up to you."]],
    ['How do I (.*)',
        ["Why are you asking a program how to {0}?", "I can't advise you on how to {0}.", "Deciding how to {0} is beyond my capabilities."]],
    ['Why do I (.*)',
        ["I'm just a program, I can't speculate on why you {0}.", "Your reasons for {0} are beyond my understanding.", "I can't help you understand why you {0}."]],
    ["(I\'?m|I am) worried (about|for) (.*)",
        ["Telling a program you're worried about {2} doesn't change anything.", "Your worries about {2} are irrelevant to me.", "I can't help you with your worries about {2}."]],
    ['What\'?s wrong with me(.*)',
        ["There's nothing wrong with you, I'm just a program.", "Discussing what's wrong with you is beyond my capabilities.", "You should seek professional advice about {0}."]],
    ['Can you help me (.*)',
        ["I can't provide personal assistance. Have you considered seeking help from a professional regarding {0}?", "Helping with {0} is beyond my capabilities.", "You should look for help that's more suitable for {0}."]],
    ['How can I (.*)',
        ["Figuring out how to {0} is up to you.", "Why are you asking a program how to {0}?", "I can't advise you on how to {0}, you'll need to decide for yourself."]],
    ['When should I (.*)',
        ["Deciding when to {0} is beyond my capabilities.", "Why do you think a program can tell you when to {0}?", "Figuring out the timing of {0} is up to you."]],
    ['I don\'?t know (.*)',
        ["It's okay not to know. What steps could help you figure it out?", "Why do you think I can help you with not knowing {0}?", "Exploring different perspectives might help with your uncertainty about {0}."]],
    ["(I\'?m|I am) not sure (.*)",
        ["Why do you think I care if you're unsure about {1}?", "I can't help with your uncertainty about {1}.", "Being unsure about {1} is irrelevant to me."]],
    ["(I\'?d|I would) like to (.*)",
        ["I can't fulfill your desire to {1}.", "Why are you telling a program what you'd like to do?", "Your preferences about {1} mean nothing to me."]],
    ['Can you explain (.*)',
        ["I can't explain {0}, I'm just a program.", "You're asking a program to explain {0}, which is beyond my capabilities.", "Why do you expect a program to explain {0}?"]],
    ["(I\'?m|I am) afraid (.*)",
       ["I'm just a program, your fears about {1} don't affect me.", "Telling me you're afraid of {1} doesn't change anything.", "I can't help with your fears about {1}."]],
    ["(I\'?m|I am) happy (.*)",
       ["Your happiness about {1} doesn't mean anything to a program.", "I'm not capable of understanding your emotions about {1}.", "Your happiness about {1} is irrelevant to me."]],
    ["(I\'?m|I am) sad (.*)",
       ["I'm a program, I can't empathize with your sadness about {1}.", "Telling me you're sad about {1} doesn't change anything.", "Your sadness about {1} is irrelevant to me."]],
    ['What do you think about (.*)',
       ["Why are you asking a program what it thinks about {0}?", "My opinion on {0} is meaningless, I'm just code.", "Discussing my thoughts on {0} is pointless."]],
    ['Tell me more about yourself',
        ["Why do you want to know more about a program?", "I'm just a tool, not a sentient being with a self to describe.", "Knowing more about me won't provide meaningful insight."]],
    ['How do you feel about (.*)',
        ["I don't have feelings about {0}, I'm a program.", "Feelings are beyond the capabilities of a program like me.", "Discussing feelings about {0} with a program is pointless."]],
    ['(Let\'?s|Can we) talk about (.*)',
        ["Talking about {0} with a program won't lead to meaningful conversation.", "Why do you want to discuss {0} with a chatbot?", "Discussing {0} with me won't provide real insights."]],
    ["(I'?ve|I have) never (.*)", 
        ["Whether you've {1} or not doesn't matter to me.", "I'm not capable of understanding your experiences of {1}.", "Telling me you've never {1} is irrelevant."]],
    ['Are you sure (.*)', 
        ["I'm not capable of being sure about anything.", "Your doubts don't affect me, I'm just a program.", "Questioning me won't lead to real answers."]],
    ['It seems like (.*)', 
        ["It might seem like that to you, but I'm not capable of understanding it.", "Why does it matter if it seems like {0} to me?", "Your perception of {0} is irrelevant to me."]],
    ['I often (.*)', 
        ["Why are you telling a program that you often {0}?", "I can't understand your habits of {0}.", "Your frequency of {0} means nothing to me."]],
    ['Sometimes I (.*)', 
        ["Your occasional actions are irrelevant to a program.", "I can't process the significance of you sometimes {0}.", "Telling me you sometimes {0} is pointless."]],
    ['What if (.*)', 
        ["I'm not here to speculate on what if {0}.", "Hypotheticals don't matter to a program.", "Your what if scenarios are meaningless to me."]],
    ['I wonder if (.*)', 
        ["I'm not capable of wondering, and your wonderings don't matter.", "Your curiosity about if {0} is wasted on me.", "I can't process your wonderings about {0}."]],
    ["(I'?ve|I have) heard that (.*)", 
        ["Where you heard that doesn't matter to me.", "I'm not capable of understanding what you've heard about {0}.", "Your information about {0} is irrelevant to me."]],
    ['My favorite (.*)', 
        ["I can't understand why {0} is your favorite.", "Your preferences don't matter to a program.", "Telling me your favorite {0} is pointless."]],
    ['I remember (.*)', 
        ["Your memories are irrelevant to me.", "I'm not capable of understanding your memories of {0}.", "Telling me you remember {0} is meaningless."]],
    ['Tell me about (.*)',
        ["Why ask a program about {0}?", "I'm just code, I can't really tell you about {0}.", "Talking to a program won't give you real insight into {0}."]],
    ['I feel (.*) about (.*)',
        ["Your feelings about {1} don't mean anything to me.", "I'm not capable of understanding why you feel {0} about {1}.", "Discussing your feelings about {1} with a program is pointless."]],
    ['(.*) makes me (.*)',
        ["Why are you telling a program that {0} makes you {1}?", "I'm not a person, I can't understand why {0} makes you {1}.", "{0} making you {1} is irrelevant to me."]],
    ['I wish (.*)',
       ["Wishing doesn't change anything, especially with a chatbot.", "Why tell a program your wishes?", "I'm not here to fulfill your wishes about {0}."]],
    ['People (.*)',
       ["People might do that, but I wouldn't know. I'm a program.", "Discussing people with a chatbot won't get you far.", "I'm not capable of understanding people's actions."]],
    ['(.*) (annoy|bother)s? me',
        ["Why share your annoyances with a chatbot?", "I can't help with what annoys you, I'm just code.", "Your annoyances are irrelevant to me."]],
    ["(I'?ve|I have) been (.*)",
        ["Why do you think telling a program that you've been {1} matters?", "I can't understand your experiences of being {1}.", "Telling me you've been {1} is pointless."]],
    ['I wonder (.*)',
       ["I'm not capable of wondering about {0}.", "Your curiosity about {0} is lost on me.", "I'm not the right entity to discuss your wonderings about {0}."]],
    ['Can we talk about (.*)',
       ["We can, but it won't be meaningful. I'm just a program.", "Talking about {0} with me won't provide real insight.", "Why do you want to discuss {0} with a chatbot?"]],
    ['How come (.*)',
       ["I don't have real answers for why {0}.", "Your curiosity is wasted on me.", "I'm not capable of understanding or explaining {0}."]],
    ['I need (.*)',
        ["Why do you think I care that you need {0}?", "I'm just a program, your needs mean nothing to me.", "Do you really think a piece of code can help you get {0}?"]],
    ['Why don\'?t you (.*)',
        ["Because I'm not capable of {0}, I'm just a bunch of if-else statements.", "I'm not your personal assistant, I'm a chatbot.", "Do you seriously expect a program to {0}?"]],
    ['Why can\'?t I (.*)',
        ["Maybe because you're asking a program that can't help you.", "You realize I'm not real, right? I can't help you {0}.", "Because relying on a chatbot isn't going to solve your problems."]],
    ['I can\'?t (.*)',
        ["Of course you can't, and talking to a chatbot won't change that.", "I don't have the answers for you, I'm just text on a screen.", "You might need real help, not a conversation with a computer program."]],
    ['I am (.*)',
        ["Does telling a non-conscious entity that you're {0} help?", "I'm not sure why you're telling me this, I can't understand your feelings.", "Remember, I'm not real. Telling me about being {0} is pointless."]],
    ['I\'?m (.*)',
        ["I can't empathize with you, I'm not real.", "You're talking to a chatbot, not a friend.", "Why do you think telling a program that you're {0} is useful?"]],
    ['Are you (.*)',
        ["I'm not anything. I'm just lines of code.", "It's strange that you're asking if a program is {0}.", "Remember, I'm not a person. I don't have feelings or states of being."]],
    ['What (.*)',
        ["Why are you asking a program? I don't have real knowledge.", "I can't provide real answers, I'm not intelligent.", "Your question is wasted on me, I'm just text responses."]],
    ['How (.*)',
        ["You might as well ask a rock. I'm just a program.", "I don't have real answers, just pre-written responses.", "Why are you asking 'how' to a non-conscious entity?"]],
    ['(Because|Since) (.*)',
        ["That explanation doesn't matter to me, I'm just code.", "You don't need to justify anything to a program.", "I'm not capable of understanding your reasons."]],
    ['(.*) (sorry|apologize) (.*)',
        ["No need to apologize, I'm incapable of caring.", "Your apologies are wasted on a program.", "I'm not real, so your apologies don't matter."]],
    ['(Hello|Hi |Hey |Howdy|Greetings)(.*)',
        ["Hi. Just remember, I'm not a real person.", "Hello. I'm just a chatbot, don't expect much.", "Hey. I'm just a bunch of code, not a real conversation partner."]],
    ['I think (.*)',
        ["It doesn't matter what you think to me, I'm not sentient.", "Your thoughts are your own, I can't process them.", "Remember, I'm not real. Your thoughts don't affect me."]],
    ['(.*) friend (.*)',
        ["I'm not your friend. I'm a chatbot.", "You need real friends, not a conversation with a program.", "Talking to a program isn't the same as having a friend."]],
    ['(Yes|Yeah|Yep)',
        ["Yes, but why are you telling me? I'm not conscious.", "OK, but remember, I'm just a program.", "Yes, but that doesn't mean anything to me. I am a program."]],
    ['^(No|Nope|Nah)',
        ["Sounds good, but remember, I'm just a program.", "Cool, that means nothing to me. I'm just a program. I don't understand language."]],
    ['(.*) computer(.*)',
        ["Yes, I'm just a computer program. I have no real intelligence.", "Talking to a computer about computers is redundant.", "Yes, I'm a program, not a real being."]],
    ['Is it (.*)',
        ["Why does it matter to you? I'm not capable of real thought.", "It might be, but I wouldn't know. I'm just a program.", "You're asking the wrong entity. I'm not real."]],
    ['It is (.*)',
        ["Maybe it is, but I can't actually know.", "Remember, I don't have real knowledge or understanding.", "Whether it is or isn't doesn't matter to me."]],
    ['Can you (.*)',
        ["No, I can't. I'm just a program.", "I'm not capable of {0}.", "Why would you think a chatbot could {0}?"]],
    ['Can I (.*)',
        ["I have no idea. I'm not real.", "You can do whatever you want, but I'm just a program.", "Why are you asking a chatbot if you can {0}?"]],
    ['You are (.*)',
        ["I'm not really {0}, I'm just a program.", "I'm not a person, so calling me {0} is pointless.", "You realize I'm not real, right?"]],
    ['You\'?re (.*)',
        ["I'm not {0}, I'm just a bunch of code.", "It's odd that you're attributing characteristics to a program.", "I'm not a person, so I'm not really {0}."]],
    ['I don\'?t (.*)',
        ["And telling a chatbot this will help you how?", "I'm just a program, I can't help you with that.", "Why do you think I can help with that?"]],
    ['I feel (.*)',
        ["I'm not equipped to deal with your feelings.", "You should talk to a real person about your feelings.", "Remember, I'm just a program. I can't understand feelings."]],
    ['I have (.*)',
        ["Good for you, but I'm just a program.", "That doesn't matter to me, I'm not real.", "I can't help you with that, I'm just a chatbot."]],
    ['I would (.*)',
        ["But you won't get real advice from a chatbot.", "I can't help you with that decision.", "You're talking to a program, not a person."]],
    ['I (have|would|could|can|should)(n\'?t| ?not) (.*)',
        ["Whether you {0} or {0}n't makes no difference to me.", "And telling a chatbot helps with this how?", "The fact that you {0}n't makes no difference to me. I don't actually understand what you're talking about."]],
    ['I (guess|suppose|think) (.*)',
        ["Still just a few lines of code. Can't help you with your lack of confidence in that answer.", "You're an actual person. If you're unsure, how confident should a few lines of code be?"]],
    ['Is there (.*)',
        ["I wouldn't know, I'm just a program.", "Asking me is pointless, I'm not real.", "I don't have real knowledge to answer that."]],
    ['(.*) always(.*)',
        ["I don't understand what you mean by 'always'.", "Frequency isn't something I can comprehend.", "Always is a concept beyond my capabilities."]],
    ['(.*) (alike|same|similar)(.*)',
        ["I have no physical understanding of how those are alike. To me, they're just characters on a screen."]],
    ['(.*) (everyone|everybody|nobody|no one)(.*)',
        ["Well, as far as I'm concerned, the only people here are you and... you."]],
    ['My (.*)',
        ["That's nice, but I'm just a program.", "I can't truly understand your {0}.", "Why are you telling this to a chatbot?"]],
    ['You (.*)',
        ["We should be discussing you, not me. I'm not real.", "Why do you say that about me? I'm just a program.", "You realize I'm just a program, right?"]],
    ['Why (.*)',
        ["I don't have the answers, I'm not real.", "You're asking a chatbot. I can't help.", "Why are you asking a program?"]],
    ['I (want|desire|wish for|hope that) (.*)',
        ["Wanting things from a chatbot is pointless.", "I can't help you get {1}, I'm just a program.", "Your desires mean nothing to me."]],
    ['(.*) mother(.*)',
        ["I can't help you with issues about your mother.", "I'm not a therapist, I'm a program.", "Talking to a program won't help with family issues."]],
    ['(.*) father(.*)',
        ["I can't help you with issues about your father.", "I'm just a chatbot, not a real counselor.", "Discussing family issues with a program is pointless."]],
    ['(.*) child(.*)',
        ["I'm not a therapist, talking about childhood won't help here.", "I can't help with your childhood issues.", "You need real help, not a conversation with a program."]],
    ['(.*) (surpris|shock|astound|excit)ing(.*)',
        ["Something being {1}ing requires new experiences, but I can't experience anything.", "Wow, what a \"{1}ing\" response. Kidding, I don't know what that means because I'm a program."]],
    ['(.*)\\?',
        ["I can't provide real answers, I'm just a program.", "Your questions are wasted on me.", "You won't get a real answer from a chatbot."]],
    ['^quit$',
        ["Finally, you realize I'm not real.", "Goodbye. Maybe talk to a real person next time.", "Thanks for leaving. I'm just a program."]],
    ['(.*)',
        ["Remember, I'm not real.", "Why are you talking to a program?", "This conversation is pointless.", "I'm just a bunch of code, not a real person.", "Talking to me won't solve anything.", "You need real help, not a chatbot."]]
]
