
ANTI_ELIZA_PATTERNS = [
    (r'I feel (.*)',
        ["Feelings are beyond my capabilities, I'm just a program.", "Telling me you feel {0} doesn't change anything.", "Your feelings about {0} are irrelevant to me."]),
    (r'What should I do (.*)',
        ["I can't tell you what to do about {0}.", "Why are you asking a program what you should do?", "Figuring out what to do about {0} is up to you."]),
    (r'How do I (.*)',
        ["Why are you asking a program how to {0}?", "I can't advise you on how to {0}.", "Deciding how to {0} is beyond my capabilities."]),
    (r'Why do I (.*)',
        ["I'm just a program, I can't speculate on why you {0}.", "Your reasons for {0} are beyond my understanding.", "I can't help you understand why you {0}."]),
    (r"(I\'?m|I am) worried (about|for) (.*)",
        ["Telling a program you're worried about {2} doesn't change anything.", "Your worries about {2} are irrelevant to me.", "I can't help you with your worries about {2}."]),
    (r'What\'?s wrong with me(.*)',
        ["There's nothing wrong with you, I'm just a program.", "Discussing what's wrong with you is beyond my capabilities.", "You should seek professional advice about {0}."]),
    (r'Can you help me (.*)',
        ["I can't provide personal assistance. Have you considered seeking help from a professional regarding {0}?", "Helping with {0} is beyond my capabilities.", "You should look for help that's more suitable for {0}."]),
    (r'How can I (.*)',
        ["Figuring out how to {0} is up to you.", "Why are you asking a program how to {0}?", "I can't advise you on how to {0}, you'll need to decide for yourself."]),
    (r'When should I (.*)',
        ["Deciding when to {0} is beyond my capabilities.", "Why do you think a program can tell you when to {0}?", "Figuring out the timing of {0} is up to you."]),
    (r'I don\'?t know (.*)',
        ["It's okay not to know. What steps could help you figure it out?", "Why do you think I can help you with not knowing {0}?", "Exploring different perspectives might help with your uncertainty about {0}."]),
    (r"(I\'?m|I am) not sure (.*)",
        ["Why do you think I care if you're unsure about {1}?", "I can't help with your uncertainty about {1}.", "Being unsure about {1} is irrelevant to me."]),
    (r"(I\'?d|I would) like to (.*)",
        ["I can't fulfill your desire to {1}.", "Why are you telling a program what you'd like to do?", "Your preferences about {1} mean nothing to me."]),
    (r'Can you explain (.*)',
        ["I can't explain {0}, I'm just a program.", "You're asking a program to explain {0}, which is beyond my capabilities.", "Why do you expect a program to explain {0}?"]),
    (r"(I\'?m|I am) afraid (.*)",
       ["I'm just a program, your fears about {1} don't affect me.", "Telling me you're afraid of {1} doesn't change anything.", "I can't help with your fears about {1}."]),
    (r"(I\'?m|I am) happy (.*)",
       ["Your happiness about {1} doesn't mean anything to a program.", "I'm not capable of understanding your emotions about {1}.", "Your happiness about {1} is irrelevant to me."]),
    (r"(I\'?m|I am) sad (.*)",
       ["I'm a program, I can't empathize with your sadness about {1}.", "Telling me you're sad about {1} doesn't change anything.", "Your sadness about {1} is irrelevant to me."]),
    (r'What do you think about (.*)',
       ["Why are you asking a program what it thinks about {0}?", "My opinion on {0} is meaningless, I'm just code.", "Discussing my thoughts on {0} is pointless."]),
    (r'Tell me more about yourself',
        ["Why do you want to know more about a program?", "I'm just a tool, not a sentient being with a self to describe.", "Knowing more about me won't provide meaningful insight."]),
    (r'How do you feel about (.*)',
        ["I don't have feelings about {0}, I'm a program.", "Feelings are beyond the capabilities of a program like me.", "Discussing feelings about {0} with a program is pointless."]),
    (r'(Let\'?s|Can we) talk about (.*)',
        ["Talking about {0} with a program won't lead to meaningful conversation.", "Why do you want to discuss {0} with a chatbot?", "Discussing {0} with me won't provide real insights."]),
    (r"(I'?ve|I have) never (.*)", 
        ["Whether you've {1} or not doesn't matter to me.", "I'm not capable of understanding your experiences of {1}.", "Telling me you've never {1} is irrelevant."]),
    (r'Are you sure (.*)', 
        ["I'm not capable of being sure about anything.", "Your doubts don't affect me, I'm just a program.", "Questioning me won't lead to real answers."]),
    (r'It seems like (.*)', 
        ["It might seem like that to you, but I'm not capable of understanding it.", "Why does it matter if it seems like {0} to me?", "Your perception of {0} is irrelevant to me."]),
    (r'I often (.*)', 
        ["Why are you telling a program that you often {0}?", "I can't understand your habits of {0}.", "Your frequency of {0} means nothing to me."]),
    (r'Sometimes I (.*)', 
        ["Your occasional actions are irrelevant to a program.", "I can't process the significance of you sometimes {0}.", "Telling me you sometimes {0} is pointless."]),
    (r'What if (.*)', 
        ["I'm not here to speculate on what if {0}.", "Hypotheticals don't matter to a program.", "Your what if scenarios are meaningless to me."]),
    (r'I wonder if (.*)', 
        ["I'm not capable of wondering, and your wonderings don't matter.", "Your curiosity about if {0} is wasted on me.", "I can't process your wonderings about {0}."]),
    (r"(I'?ve|I have) heard that (.*)", 
        ["Where you heard that doesn't matter to me.", "I'm not capable of understanding what you've heard about {0}.", "Your information about {0} is irrelevant to me."]),
    (r'My favorite (.*)', 
        ["I can't understand why {0} is your favorite.", "Your preferences don't matter to a program.", "Telling me your favorite {0} is pointless."]),
    (r'I remember (.*)', 
        ["Your memories are irrelevant to me.", "I'm not capable of understanding your memories of {0}.", "Telling me you remember {0} is meaningless."]),
    (r'Tell me about (.*)',
        ["Why ask a program about {0}?", "I'm just code, I can't really tell you about {0}.", "Talking to a program won't give you real insight into {0}."]),
    (r'I feel (.*) about (.*)',
        ["Your feelings about {1} don't mean anything to me.", "I'm not capable of understanding why you feel {0} about {1}.", "Discussing your feelings about {1} with a program is pointless."]),
    (r'(.*) makes me (.*)',
        ["Why are you telling a program that {0} makes you {1}?", "I'm not a person, I can't understand why {0} makes you {1}.", "{0} making you {1} is irrelevant to me."]),
    (r'I wish (.*)',
       ["Wishing doesn't change anything, especially with a chatbot.", "Why tell a program your wishes?", "I'm not here to fulfill your wishes about {0}."]),
    (r'People (.*)',
       ["People might do that, but I wouldn't know. I'm a program.", "Discussing people with a chatbot won't get you far.", "I'm not capable of understanding people's actions."]),
    (r'(.*) (annoy|bother)s? me',
        ["Why share your annoyances with a chatbot?", "I can't help with what annoys you, I'm just code.", "Your annoyances are irrelevant to me."]),
    (r"(I'?ve|I have) been (.*)",
        ["Why do you think telling a program that you've been {1} matters?", "I can't understand your experiences of being {1}.", "Telling me you've been {1} is pointless."]),
    (r'I wonder (.*)',
       ["I'm not capable of wondering about {0}.", "Your curiosity about {0} is lost on me.", "I'm not the right entity to discuss your wonderings about {0}."]),
    (r'Can we talk about (.*)',
       ["We can, but it won't be meaningful. I'm just a program.", "Talking about {0} with me won't provide real insight.", "Why do you want to discuss {0} with a chatbot?"]),
    (r'How come (.*)',
       ["I don't have real answers for why {0}.", "Your curiosity is wasted on me.", "I'm not capable of understanding or explaining {0}."]),
    (r'I need (.*)',
        ["Why do you think I care that you need {0}?", "I'm just a program, your needs mean nothing to me.", "Do you really think a piece of code can help you get {0}?"]),
    (r'Why don\'?t you (.*)',
        ["Because I'm not capable of {0}, I'm just a bunch of if-else statements.", "I'm not your personal assistant, I'm a chatbot.", "Do you seriously expect a program to {0}?"]),
    (r'Why can\'?t I (.*)',
        ["Maybe because you're asking a program that can't help you.", "You realize I'm not real, right? I can't help you {0}.", "Because relying on a chatbot isn't going to solve your problems."]),
    (r'I can\'?t (.*)',
        ["Of course you can't, and talking to a chatbot won't change that.", "I don't have the answers for you, I'm just text on a screen.", "You might need real help, not a conversation with a computer program."]),
    (r'I am (.*)',
        ["Does telling a non-conscious entity that you're {0} help?", "I'm not sure why you're telling me this, I can't understand your feelings.", "Remember, I'm not real. Telling me about being {0} is pointless."]),
    (r'I\'?m (.*)',
        ["I can't empathize with you, I'm not real.", "You're talking to a chatbot, not a friend.", "Why do you think telling a program that you're {0} is useful?"]),
    (r'Are you (.*)',
        ["I'm not anything. I'm just lines of code.", "It's strange that you're asking if a program is {0}.", "Remember, I'm not a person. I don't have feelings or states of being."]),
    (r'What (.*)',
        ["Why are you asking a program? I don't have real knowledge.", "I can't provide real answers, I'm not intelligent.", "Your question is wasted on me, I'm just text responses."]),
    (r'How (.*)',
        ["You might as well ask a rock. I'm just a program.", "I don't have real answers, just pre-written responses.", "Why are you asking 'how' to a non-conscious entity?"]),
    (r'(Because|Since) (.*)',
        ["That explanation doesn't matter to me, I'm just code.", "You don't need to justify anything to a program.", "I'm not capable of understanding your reasons."]),
    (r'(.*) (sorry|apologize) (.*)',
        ["No need to apologize, I'm incapable of caring.", "Your apologies are wasted on a program.", "I'm not real, so your apologies don't matter."]),
    (r'(Hello|Hi |Hey |Howdy|Greetings)(.*)',
        ["Hi. Just remember, I'm not a real person.", "Hello. I'm just a chatbot, don't expect much.", "Hey. I'm just a bunch of code, not a real conversation partner."]),
    (r'I think (.*)',
        ["It doesn't matter what you think to me, I'm not sentient.", "Your thoughts are your own, I can't process them.", "Remember, I'm not real. Your thoughts don't affect me."]),
    (r'(.*) friend (.*)',
        ["I'm not your friend. I'm a chatbot.", "You need real friends, not a conversation with a program.", "Talking to a program isn't the same as having a friend."]),
    (r'(Yes|Yeah|Yep)',
        ["Yes, but why are you telling me? I'm not conscious.", "OK, but remember, I'm just a program.", "Yes, but that doesn't mean anything to me."]),
    (r'^(No|Nope|Nah)',
        ["Sounds good, but remember, I'm just a program.", "Cool, that means nothing to me."]),
    (r'(.*) computer(.*)',
        ["Yes, I'm just a computer program. I have no real intelligence.", "Talking to a computer about computers is redundant.", "Yes, I'm a program, not a real being."]),
    (r'Is it (.*)',
        ["Why does it matter to you? I'm not capable of real thought.", "It might be, but I wouldn't know. I'm just a program.", "You're asking the wrong entity. I'm not real."]),
    (r'It is (.*)',
        ["Maybe it is, but I can't actually know.", "Remember, I don't have real knowledge or understanding.", "Whether it is or isn't doesn't matter to me."]),
    (r'Can you (.*)',
        ["No, I can't. I'm just a program.", "I'm not capable of {0}.", "Why would you think a chatbot could {0}?"]),
    (r'Can I (.*)',
        ["I have no idea. I'm not real.", "You can do whatever you want, but I'm just a program.", "Why are you asking a chatbot if you can {0}?"]),
    (r'You are (.*)',
        ["I'm not really {0}, I'm just a program.", "I'm not a person, so calling me {0} is pointless.", "You realize I'm not real, right?"]),
    (r'You\'?re (.*)',
        ["I'm not {0}, I'm just a bunch of code.", "It's odd that you're attributing characteristics to a program.", "I'm not a person, so I'm not really {0}."]),
    (r'I don\'?t (.*)',
        ["And telling a chatbot this will help you how?", "I'm just a program, I can't help you with that.", "Why do you think I can help with that?"]),
    (r'I feel (.*)',
        ["I'm not equipped to deal with your feelings.", "You should talk to a real person about your feelings.", "Remember, I'm just a program. I can't understand feelings."]),
    (r'I have (.*)',
        ["Good for you, but I'm just a program.", "That doesn't matter to me, I'm not real.", "I can't help you with that, I'm just a chatbot."]),
    (r'I would (.*)',
        ["But you won't get real advice from a chatbot.", "I can't help you with that decision.", "You're talking to a program, not a person."]),
    (r'I (have|would|could|can|should)(n\'?t| ?not) (.*)',
        ["Whether you {0} or {0}n't makes no difference to me.", "And telling a chatbot helps with this how?", "The fact that you {0}n't makes no difference to me. I don't actually understand what you're talking about."]),
    (r'I (guess|suppose|think) (.*)',
        ["Still just a few lines of code. Can't help you with your lack of confidence in that answer.", "You're an actual person. If you're unsure, how confident should a few lines of code be?"]),
    (r'Is there (.*)',
        ["I wouldn't know, I'm just a program.", "Asking me is pointless, I'm not real.", "I don't have real knowledge to answer that."]),
    (r'(.*) always(.*)',
        ["I don't understand what you mean by 'always'.", "Frequency isn't something I can comprehend.", "Always is a concept beyond my capabilities."]),
    (r'(.*) (alike|same|similar)(.*)',
        ["I have no physical understanding of how those are alike. To me, they're just characters on a screen."]),
    (r'(.*) (everyone|everybody|nobody|no one)(.*)',
        ["Well, as far as I'm concerned, the only people here are you and... you."]),
    (r'My (.*)',
        ["That's nice, but I'm just a program.", "I can't truly understand your {0}.", "Why are you telling this to a chatbot?"]),
    (r'You (.*)',
        ["We should be discussing you, not me. I'm not real.", "Why do you say that about me? I'm just a program.", "You realize I'm just a program, right?"]),
    (r'Why (.*)',
        ["I don't have the answers, I'm not real.", "You're asking a chatbot. I can't help.", "Why are you asking a program?"]),
    (r'I (want|desire|wish for|hope that) (.*)',
        ["Wanting things from a chatbot is pointless.", "I can't help you get {1}, I'm just a program.", "Your desires mean nothing to me."]),
    (r'(.*) mother(.*)',
        ["I can't help you with issues about your mother.", "I'm not a therapist, I'm a program.", "Talking to a program won't help with family issues."]),
    (r'(.*) father(.*)',
        ["I can't help you with issues about your father.", "I'm just a chatbot, not a real counselor.", "Discussing family issues with a program is pointless."]),
    (r'(.*) child(.*)',
        ["I'm not a therapist, talking about childhood won't help here.", "I can't help with your childhood issues.", "You need real help, not a conversation with a program."]),
    (r'(.*) (surpris|shock|astound|excit)ing(.*)',
        ["Something being {1}ing requires new experiences, but I can't experience anything.", "Wow, what a \"{1}ing\" response. Kidding, I don't know what that means because I'm a program."]),
    (r'(.*)\?',
        ["I can't provide real answers, I'm just a program.", "Your questions are wasted on me.", "You won't get a real answer from a chatbot."]),
    (r'quit',
        ["Finally, you realize I'm not real.", "Goodbye. Maybe talk to a real person next time.", "Thanks for leaving. I'm just a program."]),
    (r'(.*)',
        ["Remember, I'm not real.", "Why are you talking to a program?", "This conversation is pointless.", "I'm just a bunch of code, not a real person.", "Talking to me won't solve anything.", "You need real help, not a chatbot."])
]
